### ISSUE TITLE
Watch command is not working

### ISSUE THREAD

**Issue by duyngha** [vietartisans/gulp#8]
I got this error when I ran the `watch` command. Can you fix it or did I something wrong?
```bash
[BS] Watching files...
[02:33:27] Starting 'mainjs'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/gulp-uglify/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at DestroyableTransform.ondata (/home/ubuntu/workspace/wp-content/plugins/bar/node_modules/readable-stream/lib/_stream_readable.js:546:20)
```

**Comment by sondoha** [comment]
This error might be js error in `main.js` file. Please post the file content here @duyngha

**Comment by duyngha** [comment]
@sondoha 
Here is the content of `main.js` file:
```javascript
/*
*  new_map
*
*  This function will render a Google Map onto the selected jQuery element
*
*  @type	function
*  @date	8/11/2013
*  @since	4.3.0
*
*  @param	$el (jQuery element)
*  @return	n/a
*/

function new_map( $el ) {
	
	// var
	var $markers = $el.find('.marker');
	
	
	// vars
	var args = {
		zoom		: 16,
		center		: new google.maps.LatLng(0, 0),
		mapTypeId	: google.maps.MapTypeId.ROADMAP
	};
	
	
	// create map	        	
	var map = new google.maps.Map( $el[0], args);
	
	
	// add a markers reference
	map.markers = [];
	
	
	// add markers
	$markers.each(function(){
		
    	add_marker( jQuery(this), map );
		
	});
	
	
	// center map
	center_map( map );
	
	
	// return
	return map;
	
}

/*
*  add_marker
*
*  This function will add a marker to the selected Google Map
*
*  @type	function
*  @date	8/11/2013
*  @since	4.3.0
*
*  @param	$marker (jQuery element)
*  @param	map (Google Map object)
*  @return	n/a
*/

function add_marker( $marker, map ) {

	// var
	var latlng = new google.maps.LatLng( $marker.attr('data-lat'), $marker.attr('data-lng') );

	// create marker
	var marker = new google.maps.Marker({
		position	: latlng,
		map			: map
	});

	// add to array
	map.markers.push( marker );

	// if marker contains HTML, add it to an infoWindow
	if( $marker.html() )
	{
		// create info window
		var infowindow = new google.maps.InfoWindow({
			content		: $marker.html()
		});

		// show info window when marker is clicked
		google.maps.event.addListener(marker, 'click', function() {

			infowindow.open( map, marker );

		});
	}

}

/*
*  center_map
*
*  This function will center the map, showing all markers attached to this map
*
*  @type	function
*  @date	8/11/2013
*  @since	4.3.0
*
*  @param	map (Google Map object)
*  @return	n/a
*/

function center_map( map ) {

	// vars
	var bounds = new google.maps.LatLngBounds();

	// loop through all markers and create bounds
	jQuery.each( map.markers, function( i, marker ){

		var latlng = new google.maps.LatLng( marker.position.lat(), marker.position.lng() );

		bounds.extend( latlng );

	});

	// only 1 marker?
	if( map.markers.length == 1 )
	{
		// set center of map
	    map.setCenter( bounds.getCenter() );
	    map.setZoom( 16 );
	}
	else
	{
		// fit to bounds
		map.fitBounds( bounds );
	}

}

/*
*  document ready
*
*  This function will render each map when the document is ready (page has loaded)
*
*  @type	function
*  @date	8/11/2013
*  @since	5.0.0
*
*  @param	n/a
*  @return	n/a
*/
// global var
var map = null;

jQuery(document).ready(function(){
    var $ = jQuery;
    
	$('.acf-map').each(function(){

		// create map
		map = new_map( $(this) );

	});
});
```

**Comment by duyngha** [comment]
@sondoha 
This happened cause we did set `devUrl` in specific dev environment
```json
  "config": {
    "devUrl": "http://bar-duy-vietartisans.c9users.io"
  }
```
